export const paths = {
  LOGIN: "/login",
  REGISTER: "/register",
  SETTINGS: "/settings",
  PROFILE: "/profile",
  DASHBOARD: "/",
  USERS: "/users",
  MEDICATION: "/medications",
  MARQUE: "/marques",
  CATEGORY: "/category",
  FORM: "/form",
  DCI: "/DCI",
  LOT: "/Lot",
  NOTIFICATION: "/notifications",
  PAGE_NOT_FOUND: "/404",
  STOCK: "/stock",
  SEARCH: "/search",
};
